# Homebrew Taps
tap "homebrew/cask"

# CLI Utilities used in setup
brew "wget"
brew "curl"
brew "dockutil"
brew "mas"
brew "duti"
brew "defaultbrowser"

# Defaults
#REPLACE_ME_DEFAULT_SHELL_FORMULAES
cask "REPLACE_ME_DEFAULT_EDITOR"
cask "REPLACE_ME_DEFAULT_BROWSER"
cask "REPLACE_ME_DEFAULT_ARCHIVE_TOOL"

# Run while running installer script
cask "macs-fan-control"
